name: Web Conformance
on:
  push:
    branches: [main, v2]
    tags: ['v*']
  pull_request:
    branches: [main, v2]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-web-chrome-conformance-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-web-chrome-conformance-
      - name: testwebchromeconformance
        run: make testwebchromeconformance
  firefox:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-web-firefox-conformance-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-web-firefox-conformance-
      - name: testwebfirefoxconformance
        run: make testwebfirefoxconformance
  safari:
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-web-safari-conformance-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-web-safari-conformance-
      - name: testwebsafariconformance
        run: make testwebsafariconformance
  node:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-web-node-conformance-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-web-node-conformance-
      - name: testwebnodeconformance
        run: make testwebnodeconformance
